### ISSUE TITLE
A compose() with reduce() and multiple args

### ISSUE THREAD

**Issue by solendil** [getify/Functional-Light-JS#15]
I understand that your chapter about Alternate Implementations for `compose()` is a way to make your reader think about the concept. 

So I guess it's a success: it stroke me as obvious that there is another (maybe simpler) way to make the `compose()` with `reduce()` accept multiple args: by handling the first call with the given arguments then subsequent calls with `reduce()`:

``` javascript
function compose2(...fns) {
    return function composed(...result){
        var first = fns.pop()(...result);
        return fns.reverse().reduce( function reducer(result,fn){
            return fn( result );
        }, first );
    };
}
```

Though I'm quite proud of myself, I'm not quite sure it was a matter for an issue :) I'll let you judge.

**Comment by dtipson** [comment]
This might just be to taste (since imo, performance is a very minor concern with compose: it's very rare that anyone composes thousands of functions, so intelligibility and reliability are more important), but I find the recursive versions of compose somewhat convoluted/confusing to follow.  There's a reverse, a reverse of a reverse, and so on, so that by the time `pipe` is defined, there's yet another reverse of the entire thing.

It's true that if you wanted to use rest arguments with non-recursive versions, it's obviously more natural to write pipe first, because it gives you the initial function syntactically for free (whereas with compose, the initial function would be in the tail position, so not easy to get at with rest params):

```
const pipe = (fn,...fns) => (...args) => fns.reduce( (acc, f) => f(acc), fn(...args));
const compose = (...fns) => pipe(...fns.reverse());
```

But no rest argument reversing is needed to express compose recursively, because as it turns out the outwards->inwards nesting logic of the recursion can handle that for you, and in a way that's actually interestingly similar to the non-variadic version `f=>g=>x=>f(g(x));` (i.e. arguments to the right go inside arguments on the left):

```
const compose  = (fn, ...rest) =>
  rest.length === 0 ?
    (fn||(x=>x)) :
    (...args) => fn(compose(...rest)(...args));
```

One additional thing of interest is going on in that recursive version: if NO arguments are passed to compose, it still returns the Identity combinator.  That's useful because if you ever happen to be _dynamically_ deciding what functions to pass to compose, then it can still handle the empty case (i.e. if you have an array representing your functional pipeline, and you happen to remove all the items from it at some point, then calling the resulting composed function with a value just returns that value back unaltered instead of an error).

**Comment by yurrriq** [comment]
For a variadic `compose`, why not use `foldr`? I really need to read the text so my comments can be grounded in it and thus more coherent. It seems silly to me to do any reversing at all here.

**Comment by yurrriq** [comment]
You could alternatively do `foldl (flip (.)) id`.

**Comment by getify** [comment]
As for performance, one common place I use composition is to create a transducer function that will receive and transform each value as it comes through a lazy sequence (like an observable, etc), which means that function could easily be called hundreds or thousands of times. Regardless of whether it's a composition of 2, 3, or 10 functions, when it's being repeated that often, performance slow-downs can add up. So I'd say in that perspective, it's not the performance of `compose(..)` itself that matters, but the performance of the composed function it creates, which matters most.

**Comment by getify** [comment]
@solendil -- yep, that works too. It feels a little less FP'y to mutate an array like that, but I've done similar in other utilities in the text, so it's totally fair game. Thanks!

@dtipson -- Interesting variation on the recursive call option. Will consider adding something like it to the text. Thanks!

**Comment by dtipson** [comment]
If so, I don't deserve credit: I'm pretty sure it was a pattern someone else turned me onto.  I wrote about my exploration of [creating compose here](https://medium.com/@dtipson/creating-an-es6ish-compose-in-javascript-ac580b95104a) and while I was pretty sure I put a link to and credited the gist that inspired the final section/addendum, it looks like I lost track and didn't.  If whomever is reading this knows who did spell out something similar, please link/update me so I can do so (I feel like it was somebody's gist?).

Also to @getify more directly: the use in transducers is actually a really good point that I honestly hadn't considered.  I mean, it _should_ have been obvious to me: if compose is going to be claimed as a central ethic/pattern in crafting FP javascript (something I fervently believe), then of course it's going to affect and be involved in everything throughout: from composition of higher-order runtime types (which was the usage I was thinking of) and even down to lower-level iterations over huge datasets. But you totally right: if it's going to be so central... than far from its performance being unimportant, it's actually a pretty fundamental.

How various compilers optimize different versions of this is actually something I'd love to know more about.  The recursive version I outlined, as far as I can tell, is _not_ even potentially TCO (because the recursive `compose` is not the last thing called in the recursive return).  It might be possible to rewrite it so that it is, but that might hurt either expressiveness or introduce other slowdowns. Who knows how that plays out in reality: how things could theoretically be optimized and how they are in practice optimized/compiled can be worlds apart! 

I sometimes wonder if a language built from the ground up to optimize functions piping output into the input of other functions could better satisfy both the expressiveness/artistry of how we hope to code that I think FP partially aims for and also the satisfyingly (wastes nothing, works like a Swedish watch) high performance demands that we all long for. This might be exactly what Haskell is and tries to be/do for all I know: I'm just a JS developer by cosmic accident who happened to stumble onto the FP style and felt like it satisfied the "it feels like there's something I've been missing in all this, some larger pattern" itch I'd been feeling throughout my career.

**Comment by getify** [comment]
@dtipson 

So, I got around to looking in more detail at your recursive version, to try to make sure I understood how it worked. I like it, and that approach hadn't occurred to me, but it makes sense! Thanks for getting me to think differently about it.

Wanted to provide three pieces of feedback on it that occur to me:

1. Your version is not in true recursive tail-call form, because after the recursive call to `compose(..)`, the result is passed into `fn1(..)`. That is, the `fn1(..)` will be tail-callable in general, but the `compose(..)` call won't. So this approach wouldn't be practical in the general-n sense, since it won't be able to take advantage of PTC.

   Of course, as you aptly point out, the chances of composing tens of thousands of functions where you would run into the stack limit are pretty low, so it *probably* doesn't matter.

2. It always bugs me about recursion when the base case is to simply return whatever argument was just passed in, because it means that last function call is always basically a wasted no-op. So I typically try to organize my recursion so that it prevents that last unnecessary call. You'll see in mine that I pull off two functions and use them composed, instead of just one, thereby avoiding that last call.

   My version as it currently stands fails in the case where you only pass a single argument. That's unfortunate, but it could be fixed with another `if` guard obviously.

3. I like the clever idea of returning the `identity(..)` function in the case of 0-args, but I'm wondering if that's the standard behavior for `compose(..)` utilities? Do they typically handle the 0-args and 1-arg cases?

   None of my other implementations in the text do that, so if I was going to do so, I'd want to do it for all of them and not just for this one recursive one. Have to think on whether that detail helps or creates more noise.

   It might just be that I should call out this detail of the 0-args case in its own example instead of inlining that detail into the various implementations being explored.

**Comment by getify** [comment]
For posterity (mostly just my future self)... my non-ES6 version of @dtipson's recursion:

```js
function compose(fn1,...fns) {
	if (fns.length == 0) {
		return fn1;
	}
	
	return function composed(...args){
		return fn1(
			compose( ...fns )( ...args )
		);
	};
}
```

**Comment by dtipson** [comment]
1. Yep, definitely not: fn is always called last.  I inquired above whether it would be possible to write it to be, but I think not. 

3. Of the major utility libs out there, lodash returns identity, while Ramda throws an error (in PRs, there didn't seem to be a consensus on that as necessity in particular, but it's gone back and forth as part of wider internal refactoring). I originally saw the pattern in [Redux's compose](https://github.com/reactjs/redux/blob/master/src/compose.js):  After looking into it a bit, it started to make sense to me largely because in the monoid version of compose, Endo, identity is defined as the "empty" element (just like it's 0 for summing a list, 1 for multiplying a list, etc.). 

It would also be pragmatically useful in higher-order operations where a functional pipeline is built dynamically: a `compose(...fns)` where `fns` is a bunch of non-conflicting transformations (e.g. a bunch of user-determined filters on some matrix of image pixels: if all the filters/functions are removed, there's no special case or code to handle and it's not treated as an error, the matrix value is simply left altered when the transformation pipeline is empty).

**Comment by rkichenama** [comment]
Instead of `reverse().reduce` how about `reduceRight` ? It performs reduce from the right instead of the 'standard' from the left.

**Comment by getify** [comment]
I introduce `reduceRight(...)` in a later chapter.

**Comment by getify** [comment]
Thanks for the feedback in this thread. I'm closing it for now because I think I made the improvements I needed to.

**Comment by pdme** [comment]
another option:
```
const compound = (...fns) => (...args) => fns.reverse().reduce((result, fn) => (
  fn.apply(null, [result].concat(args.slice(1)))
), args[0])
```

**Comment by pdme** [comment]
am I late to the party? https://github.com/pdme/compound

**Comment by getify** [comment]
If you mutate fns by calling reverse, it will break subsequent uses of that closure.

```js
var f = compound(foo, bar, baz);

f(42);   // fine

f(42);   // broken because fns closed over in f has been mutated.
```

Fix is to shallow-copy fns before reverse:

```js
[...fns].reverse()
```
