### ISSUE TITLE
Navigation between pages

### ISSUE THREAD

**Issue by sravan-s** [getify/Functional-Light-JS#33]
@getify,

Wouldn't it be great, if we add links to previous and next chapters at end of each chapter (something like this: https://github.com/sravan-s/Functional-Light-JS/commit/df0f3ae8fde45a710e163fb08d4c1c24959b8487). Right now, I have to navigate back or type in the chapter name at the address bar. Or is there any simple navigation trick that I have missed?

**Comment by getify** [comment]
I typically won't do those things in these book repos because the main point of the repo is not for reader consumption -- you *can* of course -- but to provide the content to the publisher. The best reading experience is in the published form (ebook or print). That said, this book may eventually end up on gitbook, but I haven't decided on that yet.

Typically, I balance these concerns by hoping that people are willing to pay for the best reading experience, while having access to the content itself for free.

**Comment by getify** [comment]
FYI: I've [updated the contribution guide](https://github.com/getify/Functional-Light-JS/blob/master/CONTRIBUTING.md#reading-experience-chaptersection-links-etc) on this topic, to help provide more clarity, especially for posterity. Thanks!
