### ISSUE TITLE
ES6 curry function in ch3

### ISSUE THREAD

**Issue by rkichenama** [getify/Functional-Light-JS#34]
I am looking over the function and it seems odd.  Is the line `(nextCurried = prevArgs =>` performing an implied variable definition without var|let|const ? And if so, would that then be hoisted to the parent scope?

**Comment by getify** [comment]
`nextCurried` is "declared" in the line before it, as one of the params (this is a common arrow-function trick to avoid needing to make a `let`/`var` decl). It's assigned the arrow function reference, because the arrow function needs to be able to recursively call itself, and arrow functions are (annoyingly) anonymous.

**Comment by rkichenama** [comment]
Ah, I see it now. Neat trick.

**Comment by Wgil** [comment]
What a good trick, I don't know if it deserves an explanation in the book since it is not straightforward to come up with its intention. The thing is that if you don't "declare it" before assigning it, it will be assigned in the outer scope. Am I right?

**Comment by estenp** [comment]
I appreciate that this trick existed in the code example, because it helped me to learn something, but I think it is useful to explain why it is used. Especially because it's not super immediately apparent that `nextCurried` is scoped globally upon removing it. I could see people unfamiliar with fat arrows not understanding the 3rd param, removing it, and continuing about their day because the curry function remains functional - perhaps stopping by the GitHub issues and searching for "nextCurried" in closed issues because, "that couldn't have just been a typo, could it...? It seems very intentional..." (ehem: ME).

Side note, in these scenarios, why wouldn't you just use the braced fat arrow syntax instead? It's way more readable than an unused param, and even makes this specific function more readable in general (IMO).

```
const curry =
    (fn, arity = fn.length) => {
        const nextCurried = 
           prevArgs => 
             nextArg => {
              const args = [ ...prevArgs, nextArg ];
              if (args.length >= arity) {
                return fn( ...args );
              }
              else {
                return nextCurried( args );
              }
            }
        return nextCurried([])
    }
```

I mean I get the point of the two examples throughout is to show one more verbose, but readable version, and one more streamlined, but cryptic version, but idk..

**Comment by getify** [comment]
> why wouldn't you just use the braced fat arrow syntax instead?

IMO, I wouldn't use the `=>` arrow syntax for these utilities, and it furthermore it's my impression that almost universally those who *would* are awfully likely to want to use the absolute minimal `=>` syntax rather than somewhere balanced "in the middle", such as with the `{ }` non-concise body form.

**Comment by estenp** [comment]
Fair enough. That’s sort of what I figured to be the reason behind it.

**Comment by getify** [comment]
> it's not super immediately apparent that nextCurried is scoped globally upon removing it

BTW, if you are using strict-mode (you should!) and you were to remove the parameter, then you would immediately be presented with an error that `nextCurried` was undefined, rather than creating the accidental global.

**Comment by estenp** [comment]
I didn't realize that. Thanks, Kyle! (And thanks for the book - it's great!)
