### ISSUE TITLE
Ch 2: `arguments` object not deprecated

### ISSUE THREAD

**Issue by shshaw** [getify/Functional-Light-JS#35]
In chapter 2, you state `As of ES5, arguments is deprecated.`, but from the information I can find, the [`arguments` object](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/arguments) itself is not deprecated, but rather the property [`Function.arguments`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/arguments) is. 

MDN's recommendation from [Deprecated and Obsolete Features](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Deprecated_and_obsolete_features) is:
> The caller and arguments [Function] properties are deprecated, because they leak the function caller. Instead of the arguments property, you should use the arguments object inside function closures.

If I'm mistaken, do you have any resources showing the deprecation of the `arguments` object?

**Comment by getify** [comment]
There's no such thing as official deprecation in this respect. Informal deprecation means influential developers telling others "stop using it", which has been pretty common in my observation. However, it'll never be actually removed from JS.

The evidence for informal deprecation of `arguments` includes the fact that its behavior was altered in strict mode (of ES5) to not be bound to its corresponding named arguments, as well as the fact that in ES6 the `...` rest operator obviates most common needs for `arguments`. Moreover, `arguments` being "array-like" instead of a real "array" has been the extremely common footgun that trips up devs, which is why it's so often frowned upon.

**Comment by shshaw** [comment]
Ah, thanks for explaining.

Perhaps rephrasing that in the chapter would make that clearer:

> With the addition of the rest operator (`...`) in ES5, it's strongly suggested that you avoid using the `arguments` object whenever possible to avoid many complications that it can introduce.
