### ISSUE TITLE
Chapter 2 Feedback

### ISSUE THREAD

**Issue by reverentgeek** [getify/Functional-Light-JS#40]
I just finished reading Chapter 2. It wasn't clear to me this was a chapter on JavaScript fundamentals. I kept expecting you to start mapping some of the features of functions to FP concepts, maybe in an overview fashion. As I read, I got more and more anxious with the mental tax of holding all this information "in memory" until the expected mapping began. For example, as I was reading about function arguments/parameters, I kept thinking, "Ok, I already know JavaScript, but _why_ is this important?"

After I finished the chapter, I went back and re-read the beginning, thinking I must have overlooked something or misunderstood its purpose. All that to say, from my perspective, you should make it *more* clear at the start of the chapter you are covering JavaScript language features that will be important for learning FP patterns in the *rest* of the book.

**Comment by getify** [comment]
I appreciate this feedback.

The intent of this chapter is not just a general JS primer, but to drill into all of the things that are true of JS functions that must be really known to understand functional programming. In particular, my perception is that you really need to get functions from the FP perspective before you can understand FP itself, and that's the intent of this chapter. The whole rest of the book expounds on FP principles, but this chapter is our foundation: the function.

I will try to make that more explicit in the chapter intro. What I don't want to do is make it sound like you can skip this chapter if you already know JS, because I don't think I'd recommend that. :)

**Comment by reverentgeek** [comment]
I agree it shouldn't be skipped. I simply made the wrong assumption, and had the wrong expectations. Making it more clear might help other readers from making the same mistake I made. The content itself was very good 👍
