### ISSUE TITLE
Suggestions for changes to less than ten words

### ISSUE THREAD

**Issue by nick-walt** [getify/Functional-Light-JS#55]
Hi Kyle, do you see this kind of edit as a valid suggestion:

*Original:* I believe very deeply that `the vastly more important role of code` is as a means of communication with other human beings.

*Modified:* I believe very deeply that `code is vastly more important` as a means of communication with other human beings.

If it is I can just collect everything I find into one *issue*, formatted clearly into their chapters, etc, for use at your discretion. I'll include original text for easy search. Cheers.

**Comment by getify** [comment]
I appreciate those kinds of suggestions, but I have contracted a copy-editor who will be going through and making all those sorts of edits. I would recommend holding off on such until they are done, so that you're not duplicating work. It's quite possible you may have further suggestions like this after the copy-edit, but I'd hate to have duplicated/colliding edits like that to juggle.

**Comment by nick-walt** [comment]
Ok, too easy :) Thanks.
