### ISSUE TITLE
Mention Ramda

### ISSUE THREAD

**Issue by flashhhh** [getify/functional-light-js#7]
Hi!

I understand the idea of explaining FP step-by-step with "homemade" examples. However, I suggest you to mention [Ramda](http://ramdajs.com/0.22.1/index.html) in later chapters when it comes to real applications.

Probably, you have a plan to publish all the external resources at the end of the book. Just wanted to make sure Ramda would be there, because it rocks and it is the most usable FP library out there for Javascript!

You could also create your own package with all those helpers and examples you coded, so people would be able to play with it rapidly.

**Comment by getify** [comment]
Actually, I plan to mention various FP libs, including Ramda of course, in the first intro chapter. I may even show a few quick code snippets just to illustrate.

But for the rest of the text I'm going to show how each utility we need (`partial(..)`, `compose(..)`, etc) is built rather than just conjuring a magic method from some library the reader is likely not already familiar with. I don't want the code snippets to be cluttered by a library's API eccentricities. Moreover, seeing how a utility is built actually reinforces some of the ideas being taught, like closure, etc.

But I will remind the reader on more than one occasion, perhaps even with a dedicated appendix, that next steps after this book are to go find the equivalent of all these utilities in an FP-friendly library like Ramda, Underscoore, etc.

**Comment by flashhhh** [comment]
Thanks for the explanation!

> But for the rest of the text I'm going to show how each utility we need (partial(..), compose(..), etc) is built rather than just conjuring a magic method from some library the reader is likely not already familiar with. I don't want the code snippets to be cluttered by a library's API eccentricities. Moreover, seeing how a utility is built actually reinforces some of the ideas being taught, like closure, etc.

Definitely, agree with this. You absolutely should show how all these utilities are built from scratch. I just wanted to make sure you're going to mention real world libraries at some point.
